#### PLAYER OPTIONS ####
[player]
# By default, Toutui integrated player is launched (works with cvlc, launched in background, the command line 
# version of vlc).
# 0: No, 1: Yes
# Launch Toutui integrated player:
# Set to 0 if you want to have vlc GUI.
cvlc = "1"
# Launch a terminal to control cvlc:
# NOTE: `cvlc` must be set to 1 if you set `cvlc_term` to 1.
cvlc_term = "0"

#### PLAYER NETWORK ####
# By default, the player is launched to "localhost:1234"
# Address:
address = "localhost"
# Port:
port = "1234"

#### COLORS (RGB) ####
[colors]
# General background color of the app:
background_color = [40, 40, 40]
# Login background color:
log_background_color = [40, 40, 40]
# Background color for section headers (e.g., "Continue Listening", "Library", etc.):
header_background_color = [60, 60, 60]
# Line color surrounding the header title:
line_header_color = [180, 180, 180]
# Background color of the book list:
list_background_color = [50, 50, 50]
# Background color for alternate rows of the book list:
list_background_color_alt_row = [60, 60, 60]
# Background color of the selected row of the book list:
list_selected_background_color = [80, 80, 80]
# Text color of the selected row of the book list:
list_selected_foreground_color = [180, 180, 180]
# Text and border color of the search bar:
search_bar_foreground_color = [180, 180, 180]
# Text and border color of the login section:
login_foreground_color = [180, 180, 180]
# Background color of the player:
player_background_color = [80, 80, 80]
